### ISSUE TITLE
Ability to test fixes

### ISSUE THREAD

**Issue by SamVerschueren** [jfmengels/eslint-ava-rule-tester#3]
I'm not sure if this is possible, or that there is another way of doing this. But I guess it would be nice if we could test the fixers as well.

Something like this maybe?

``` js
ruleTester.run('my-awesome-rule', rule, {
  fix: [
    {
      input: 'const foo = 0XFF',
      output: 'const foo = 0xFF'
    }
  ]
});
```

// @sindresorhus

**Comment by SamVerschueren** [comment]
Alright, now I see this is only a small wrapper around the ESLint rule tester. Odd that they don't seem to have it themselves...

**Comment by jfmengels** [comment]
Yes, this has the same API as ESLint's RuleTester. And it does have the ability to check fixes, but the documentation for it is really lacking. You have the `output` field to specify the expected code output.

```js
{
  code: 'it.skip()',
  errors: [ { message: expectedErrorMessage, column: 4, line: 1 } ],
  output: 'it()'
}
````

**Comment by sindresorhus** [comment]
@jfmengels Can you add an example of it here? Even though ESLint doesn't document it very well, doesn't mean we can't make it easier for people.

**Comment by SamVerschueren** [comment]
Yes it would be nice if it was documented.

**Comment by jfmengels** [comment]
Good point

**Comment by kristianmandrup** [comment]
What is the ESlint Rule Tester!? I assume it is the tester that runs the ESlint rules on your code to see if you follow conventions specified and reports errors... 
So this library will run these tests on the Ava test files!? Trying to get the full picture! Thanks :)

**Comment by SamVerschueren** [comment]
It allows you to test rules, hence the name ;).

Example: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/test/no-new-buffer.js#L24-L80
